# See the Twitter API docs for details on potential stream parameters.
# Note thate many of the options presented in the docs are for User streams, and this application only uses the
# public API sample stream. Relevant default options are shown here. Please note that the only tested
# parameter at this time is language.
# https://dev.twitter.com/streaming/overview/request-parameters
twitter_stream_parameters:
  language: en
  track:
  follow:
  locations:
  replies:  # put 'all' here to also see reply Tweets

# Settings specific to this program
program_settings:
  read_seconds: 300 # number of seconds to connect to the Twitter sample stream and download data
  save_file: streams/stream.txt
  report_file: streams/report.csv
  report_top: 10
  report_hashtags: false
  console_output: true  # set to true if you want to see the Tweets on the screen

  # Many of the skip_words are suggestions from www.ranks.nl/stopwords
  # The rest are determined from looking at outliers in the data stream and continuously updating this list
  skip_words: a about above after again against all am an and any are aren't as at be because been before being \
   below between both but by can't cannot could couldn't did didn't do does doesn't doing don't down during \
   each few for from further had hadn't has hasn't have haven't having he he'd he'll he's her here here's hers \
   herself him himself his how how's i i'd i'll i'm i've if in into is isn't it it's its itself let's me more \
   most musn't mustn't my myself no nor not of off on once only or other ought our ours ourselves out over own same \
   shan't she she'd she'll she's should shouldn't so some such than that that's the their theirs them themselves \
   then there there's these they they'd they'll they're they've this those through to too under until up very \
   was wasn't we we'd we'll we're we've were weren't what what's when when's where where's which while who who's \
   whom won't would wouldn't you you'd you'll you're you've your yours yourself yourselves \
   RT u \ with just really get can why will back got ur one know now need
   _





